server:
  port: 7008
spring:
  security:
    oauth2:
      client:
        registration:
          auth-code: # \u5B9A\u4E49 \u6388\u6743\u7801\u6A21\u5F0F id
            provider: shehuan
            client-id: my_client
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri: http://client.shehuan.com:7008/login/oauth2/code/shehuan
            scope: read:msg
          client-creds: # \u5BA2\u6237\u7AEF\u6A21\u5F0F
            provider: shehuan
            client-id: my_client
            client-secret: 123456
            authorization-grant-type: client_credentials
            scope: read:msg
          password: # \u5BC6\u7801\u6A21\u5F0F
            provider: shehuan
            client-id: my_client
            client-secret: 123456
            authorization-grant-type: password
            scope: read:msg
        provider: # \u914D\u7F6E\u6388\u6743\u670D\u52A1\u5668\u7684\u8BA4\u8BC1\u5730\u5740\u3001\u4EE5\u53CA\u83B7\u53D6\u4EE4\u724C\u7684\u5730\u5740
          shehuan:
            authorization-uri: http://auth.shehuan.com:7006/oauth/authorize
            token-uri: http://auth.shehuan.com:7006/oauth/token

